In [ ]:
import pandas as pd
import numpy as np
import matplotlib as plt

# Leitura caminho dos dados
caminho_dados = "BaseVarejoDadosBrutos.csv"
df = pd.read_csv(caminho_dados, sep= ";")
df.head()

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA,NaN,NaN,NaN,NaN
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS,NaN,NaN,NaN,NaN
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO,NaN,NaN,NaN,NaN
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO,NaN,NaN,NaN,NaN

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 830000 entries, 0 to 829999
Data columns (total 14 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   DATA         830000 non-null  object
 1   CO_ID        830000 non-null  int64
 2   CL_ID        830000 non-null  int64
 3   CL_GENERO    830000 non-null  object
 4   CL_EC        830000 non-null  int64
 5   CL_FHL       830000 non-null  int64
 6   CL_SEG       830000 non-null  object
 7   PR_ID        830000 non-null  int64
 8   PR_CAT       830000 non-null  object
 9   PR_NOME      830000 non-null  object
 10  Unnamed: 10  0 non-null       float64
 11  Unnamed: 11  0 non-null       float64
 12  Unnamed: 12  0 non-null       float64
 13  Unnamed: 13  0 non-null       float64
dtypes: float64(4), int64(5), object(5)
memory usage: 88.7+ MB

In [10]:
df.shape

(830000, 14)


Dicionário de dados

datas, clientes, produtos, categorias e valores

1. DATA: Data da compra;  
2. CO_ID: Identificação do número de compra (número da nota fiscal);  
3. CL_ID: Identificação do cliente (número do cliente);  
4. CL_GENERO: Sexo biológico informado pelo cliente;  
2 
5. CL_EC: Estado civil do cliente:  
1: Casado ou união estával;  
2: Divorciado;  
3: Separado;  
4. Solteiro;  
5: Viúvo.  
6. CL_FHL: Número de filhos do cliente;  
7. CL_SEG: Segmentação econômica do cliente (classe A, B ou C);  
8. PR_ID: Código do produto (SKU) adquirido;  
9. PR_CAT: Categoria do produto adquirido;  
10. PR_NOME: Nome do produto adquirido.

In [14]:
df.columns

Index(['DATA', 'CO_ID', 'CL_ID', 'CL_GENERO', 'CL_EC', 'CL_FHL', 'CL_SEG',
       'PR_ID', 'PR_CAT', 'PR_NOME', 'Unnamed: 10', 'Unnamed: 11',
       'Unnamed: 12', 'Unnamed: 13'],
      dtype='object')

In [19]:
df["PR_NOME"].nunique()

118

In [20]:
df["PR_ID"].nunique()

229

In [3]:
df.describe()

,CO_ID,CL_ID,CL_EC,CL_FHL,PR_ID,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
count,830000.000000,830000.000000,830000.000000,830000.00000,830000.000000,0.0,0.0,0.0,0.0
mean,460045.089890,499.595204,2.596911,1.14654,115.051855,NaN,NaN,NaN,NaN
std,265465.247541,287.568253,1.170599,1.41696,66.129241,NaN,NaN,NaN,NaN
min,1000.000000,1.000000,1.000000,0.00000,1.000000,NaN,NaN,NaN,NaN
25%,233117.000000,254.000000,2.000000,0.00000,58.000000,NaN,NaN,NaN,NaN
50%,456517.000000,498.000000,3.000000,0.00000,115.000000,NaN,NaN,NaN,NaN
75%,690132.000000,746.000000,4.000000,2.00000,172.000000,NaN,NaN,NaN,NaN
max,919822.000000,1000.000000,5.000000,4.00000,229.000000,NaN,NaN,NaN,NaN

In [18]:
df["PR_NOME"].nunique()

118

In [ ]:
colunas = ['DATA', 'CO_ID', 'CL_ID', 'CL_GENERO', 'CL_EC', 'CL_FHL', 'CL_SEG', 'PR_ID', 'PR_CAT', 'PR_NOME']

print(df.columns.tolist())




print(df[['DATA', 'CO_ID', 'CL_ID', 'CL_GENERO', 'CL_EC', 'CL_FHL', 'CL_SEG', 'PR_ID', 'PR_CAT', 'PR_NOME']].head())

print(df[['DATA', 'CO_ID', 'CL_ID', 'CL_GENERO', 'CL_EC', 'CL_FHL', 'CL_SEG', 'PR_ID', 'PR_CAT', 'PR_NOME']].tail())

print(df[['DATA', 'CO_ID', 'CL_ID', 'CL_GENERO', 'CL_EC', 'CL_FHL', 'CL_SEG', 'PR_ID', 'PR_CAT', 'PR_NOME']].describe())

df = df[["DATA","CL_ID","PR_NOME","PR_CAT","PR_ID","CL_GENERO"]]

print(df.size)